---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kriko.
--- DateTime: 2022/1/18 8:47
---

print("Hello form Lua")
print("Lua code is capable of reading the value set from C++", cppvar)
luavar = cppvar * 3

function myluafunction(times)
    return string.rep("(-)", times)
end

function myfunction(arg)
    return cppfunction(arg)
end