---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyifei.
--- DateTime: 2022/1/18 10:34
---

print("Hello form Lua")

print("Call Cpp Function "..CCodeMyAdd(100, 1000))

function TestLuaFunction(Str)
    Ret = "Call Lua Function With Args = ".. Str
    print(Ret)
    return Ret
end